In [266]:
# Imported the csv file 
import pandas as pd
df = pd.read_csv('facility_service_data_2022_2024.csv')

df.head(5)

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,Mission Hospital Bwari II,FCT,Bwari,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,Teaching Hospital Gwagwalada II,FCT,Gwagwalada,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,Nasarawa,Lafia,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,Lagos,Surulere,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,Comprehensive Health Centre Oron,Akwa-Ibom,Oron,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk

In [267]:
# Changed the facility name, id's, state, and lga to uppercase.
df['state'] = df['state'].str.strip().str.upper()
df['facility_name'] = df['facility_name'].str.strip().str.upper()
df['facility_id'] = df['facility_id'].str.strip().str.upper()
df['lga'] = df['lga'].str.strip().str.upper()
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,128,4,3,1286,21,1279,1179,968,2024-09-13,Data Clerk
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,30/11/2024,306,20,16,722,3,43,2,1,555,8,520,427,388,2024-12-18,Data Clerk
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [268]:
# Changed the dated to pandas date and time format
cols = ["report_month", "date_submitted"]

df[cols] = df[cols].apply(
    lambda col: pd.to_datetime(col, format="mixed" ,errors="coerce")
)
df[cols]

     report_month date_submitted
0      2022-11-30     2022-12-11
1      2023-04-30     2023-05-11
2      2024-01-31     2024-02-18
3      2022-03-31     2022-04-15
4      2022-01-31     2022-02-13
...           ...            ...
4409   2024-08-31     2024-09-13
4410   2024-11-30     2024-12-18
4411   2022-04-30     2022-05-13
4412   2022-03-31     2022-04-11
4413   2024-09-30     2024-10-15

[4414 rows x 2 columns]

In [269]:
# Created a seperate column for year, month and quarter
df['year'] = df['report_month'].dt.year
df['month'] = df['report_month'].dt.month
df['quarter'] = df['report_month'].dt.quarter
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,...,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by,year,month,quarter
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,952,39,29,"2,721",23,...,2237,36,2271,1624,1396,2022-12-11,Data Clerk,2022,11,4
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,773,40,34,5094,42,...,2875,41,3722,2467,2342,2023-05-11,Data Clerk,2023,4,2
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,...,526,6,753,520,476,2024-02-18,Data Clerk,2024,1,1
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,...,375,8,451,383,358,2022-04-15,Facility Focal Person,2022,3,1
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,...,736,19,1145,685,644,2022-02-13,Data Clerk,2022,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,...,1286,21,1279,1179,968,2024-09-13,Data Clerk,2024,8,3
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,2024-11-30,306,20,16,722,3,...,555,8,520,427,388,2024-12-18,Data Clerk,2024,11,4
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,...,403,11,573,316,306,2022-05-13,M&E Officer,2022,4,2
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,...,435,8,453,405,380,2022-04-11,Facility Focal Person,2022,3,1
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,...,558,21,661,443,387,2024-10-15,Data Clerk,2024,9,3

In [270]:
# Moved the year, month and quarter column from the end to just beside the report_month column from better reading
cols = df.columns.tolist()
cols.remove('year')
cols.remove('month')
cols.remove('quarter')

cols.insert(5, 'year')
cols.insert(6, 'month')
cols.insert(7, 'quarter')
df = df[cols]
df.tail(3)

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,2022,4,2,323,3,...,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,2022,3,1,128,,...,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,2024,9,3,544,7,...,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [271]:
# validating the dates to make sure they fall under 2022 - 2024 and end of the month 
valid_dates = (
    df["report_month"].dt.year.between(2022, 2024)
    & df["report_month"].dt.is_month_end
)

df.loc[~valid_dates, "report_month"]

5      2022-05-01
10     2024-06-01
11     2023-02-01
24     2022-12-01
38     2024-12-01
          ...
4382   2023-01-01
4383   2022-03-01
4394   2024-12-01
4399   2023-12-01
4406   2023-11-01
Name: report_month, Length: 441, dtype: datetime64[ns]

In [ ]:
# Replaced ["", "N/A", "-", 'NULL', "nil"] with pandas NA
df.replace(["", "N/A", "-", 'NULL', "nil"], pd.NA, inplace= True)

In [344]:
df.head()

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,2022,11,4,952.0,39.0,...,300.0,9,8,2237.0,36,2271.0,1624.0,1396.0,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,2023,4,2,773.0,40.0,...,102.0,1,0,2875.0,41,3722.0,2467.0,2342.0,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,2024,1,1,244.0,6.0,...,58.0,1,0,526.0,6,753.0,520.0,476.0,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,2022,3,1,440.0,6.0,...,92.0,0,0,375.0,8,451.0,383.0,358.0,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,2022,1,1,76.0,0.0,...,18.0,1,0,736.0,19,1145.0,685.0,644.0,2022-02-13,Data Clerk

In [274]:
# Removed commas white spaces and convertes all the numbers from text to number 
cols = ["hts_tst", "hts_tst_pos", "tx_new", "tx_curr", "tx_ml", "pmtct_stat", "pmtct_stat_pos", "pmtct_art", "tb_screen", "tb_pos", "vl_eligible", "vl_result_received", "vl_suppressed"]

df[cols] = (df[cols].replace(",", "")
    .apply(lambda col: col.astype("string").str.strip())
    .apply(pd.to_numeric, errors="coerce"))

In [347]:
# Checking for negative values
negative_values = df[
    (df[cols] < 0).any(axis=1)
]

negative_values.head()

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
46,RIV010,TEACHING HOSPITAL AHOADA EAST II,RIVERS,AHOADA EAST,2022-06-30,2022,6,2,756.0,11.0,...,174.0,4,3,2272.0,48,3052.0,2439.0,2092.0,2022-07-21,M&E Officer
113,AKS009,PRIMARY HEALTH CENTRE IKOT EKPENE II,AKWA-IBOM,IKOT EKPENE,2024-07-31,2024,7,3,109.0,6.0,...,27.0,1,0,137.0,2,190.0,145.0,135.0,2024-08-21,Data Clerk
339,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA IBOM,ORON,2022-09-30,2022,9,3,127.0,0.0,...,27.0,0,0,1123.0,22,1113.0,687.0,649.0,2022-10-13,Facility Focal Person
510,BEN015,PRIMARY HEALTH CENTRE OTUKPO II,BENUE,OTUKPO,2022-07-31,2022,7,3,1440.0,3.0,...,18.0,0,0,764.0,9,733.0,605.0,526.0,2022-08-16,M&E Officer
582,LAG012,PRIMARY HEALTH CENTRE ALIMOSHO II,LAGOS,ALIMOSHO,2024-07-31,2024,7,3,382.0,18.0,...,82.0,1,0,597.0,7,597.0,474.0,445.0,2024-08-16,Facility Focal Person

In [276]:
# checked the number of duplicates in the dataset
df.duplicated().sum()

59

In [277]:
# Removed duplicates from the dataset
df = df.drop_duplicates(keep="first")

In [ ]:
# Checking how many null values in each column
df.isna().sum()

facility_id             0
facility_name           0
state                   0
lga                     0
report_month            0
year                    0
month                   0
quarter                 0
hts_tst                77
hts_tst_pos            78
tx_new                 76
tx_curr               139
tx_ml                   0
pmtct_stat             77
pmtct_stat_pos          0
pmtct_art               0
tb_screen              79
tb_pos                  0
vl_eligible            78
vl_result_received     77
vl_suppressed          76
date_submitted          0
reported_by             0
dtype: int64

In [ ]:
# Working on the facility master list
fm= pd.read_csv("facility_master_list.csv")
fm.head(5)

,facility_id,facility_name,state,lga,facility_level,ownership,setting,art_start_date,catchment_population,latitude,longitude
0,AKS001,Comprehensive Health Centre Uyo,Akwa Ibom,Uyo,Primary,Private,Urban,2015-04-22,79792.0,10.09626,9.47271
1,AKS002,General Hospital Ikot Ekpene,Akwa Ibom,Ikot Ekpene,Secondary,Public,Urban,2013-09-22,49951.0,7.01753,4.10253
2,AKS003,Model Primary Health Centre Eket,Akwa Ibom,Eket,Primary,Public,Rural,2022-04-04,32449.0,8.46012,3.03009
3,AKS004,Comprehensive Health Centre Etinan,Akwa Ibom,Etinan,Primary,Public,Rural,2018-09-03,193467.0,8.67776,5.11477
4,AKS005,Comprehensive Health Centre Oron,Akwa Ibom,Oron,Primary,Public,Rural,2020-08-04,72505.0,10.62470,4.38552

In [ ]:
#Infor about that csv file
fm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   facility_id           126 non-null    object
 1   facility_name         126 non-null    object
 2   state                 126 non-null    object
 3   lga                   126 non-null    object
 4   facility_level        126 non-null    object
 5   ownership             120 non-null    object
 6   setting               120 non-null    object
 7   art_start_date        126 non-null    object
 8   catchment_population  120 non-null    float64
 9   latitude              126 non-null    float64
 10  longitude             126 non-null    float64
dtypes: float64(3), object(8)
memory usage: 11.0+ KB

In [348]:
#Checking for unique values
fm["facility_id"].is_unique

True

In [ ]:
# checking duplicates from fm
master_duplicates = fm[
    fm["facility_id"].duplicated(keep=False)
]

master_duplicates

Empty DataFrame
Columns: [facility_id, facility_name, state, lga, facility_level, ownership, setting, art_start_date, catchment_population, latitude, longitude]
Index: []

In [ ]:
# checking if the facility id 
fm["facility_id"].head()

0    AKS001
1    AKS002
2    AKS003
3    AKS004
4    AKS005
Name: facility_id, dtype: object

In [ ]:
# checking how many missing values exist
fm.isna().sum()

facility_id             0
facility_name           0
state                   0
lga                     0
facility_level          0
ownership               6
setting                 6
art_start_date          0
catchment_population    6
latitude                0
longitude               0
dtype: int64

In [ ]:
# Removing duplicates from fm
fm.drop_duplicates(subset=["facility_id"], keep="first", inplace=True)

In [ ]:
# Standardizing the facility id 
fm["facility_id"] = (fm["facility_id"].astype("string").str.strip().str.upper())

In [ ]:
# Merging the facility id on both the facility master file and the facility service data 
merged = df.merge(
    fm,
    on="facility_id",
    how="outer",
    indicator=True
)

In [ ]:
# Checking the merge outcome
merged["_merge"].value_counts()

_merge
both          4175
left_only      180
right_only       5
Name: count, dtype: int64

In [ ]:
# checking the merge on the left
fmna = merged[
    merged["_merge"] == "left_only"
]
fmna.head()

,facility_id,facility_name_x,state_x,lga_x,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,state_y,lga_y,facility_level,ownership,setting,art_start_date,catchment_population,latitude,longitude,_merge
1433,LAG099,GENERAL HOSPITAL CHIKUN II,KADUNA,CHIKUN,2024-05-31,2024.0,5.0,2.0,361.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1434,LAG099,SPECIALIST HOSPITAL ALIMOSHO,LAGOS,ALIMOSHO,2023-05-31,2023.0,5.0,2.0,1093.0,23.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1435,LAG099,MODEL PRIMARY HEALTH CENTRE KADUNA NORTH,KADUNA,KADUNA NORTH,2023-04-30,2023.0,4.0,2.0,251.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1436,LAG099,COTTAGE HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2024-06-30,2024.0,6.0,2.0,1377.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1437,LAG099,MODEL PRIMARY HEALTH CENTRE KATSINA-ALA II,BENUE,KATSINA-ALA,2023-04-30,2023.0,4.0,2.0,255.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [ ]:
# checking the merge on the right
fmnaa = merged[
    merged["_merge"] == "right_only"
]
fmnaa

,facility_id,facility_name_x,state_x,lga_x,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,state_y,lga_y,facility_level,ownership,setting,art_start_date,catchment_population,latitude,longitude,_merge
4355,NEW001,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Cross River,Obudu,Primary,Private,Urban,2018-08-05,155505.0,11.31909,9.02246,right_only
4356,NEW002,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Cross River,Calabar Municipal,Primary,Public,Rural,2020-03-08,195430.0,9.40478,3.56223,right_only
4357,NEW003,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Akwa Ibom,Abak,Primary,Public,Rural,2016-08-10,70260.0,6.37644,3.46073,right_only
4358,NEW004,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Nasarawa,Karu,Secondary,Private,Urban,2014-08-25,197190.0,9.05993,7.19223,right_only
4359,NEW005,NaN,NaN,NaN,NaT,NaN,NaN,NaN,<NA>,<NA>,...,Cross River,Ikom,Primary,Public,Rural,2017-10-18,46195.0,5.01068,5.08764,right_only

In [ ]:
#Cross checking
df.shape

(4355, 23)

In [ ]:
#Cross checking
df.columns

Index(['facility_id', 'facility_name', 'state', 'lga', 'report_month', 'year',
       'month', 'quarter', 'hts_tst', 'hts_tst_pos', 'tx_new', 'tx_curr',
       'tx_ml', 'pmtct_stat', 'pmtct_stat_pos', 'pmtct_art', 'tb_screen',
       'tb_pos', 'vl_eligible', 'vl_result_received', 'vl_suppressed',
       'date_submitted', 'reported_by'],
      dtype='object')

In [ ]:
# checkingb the datatypes of the report month and date submitted
df[["report_month", "date_submitted"]].dtypes

report_month      datetime64[ns]
date_submitted    datetime64[ns]
dtype: object

In [ ]:
# Creating a list of all the columns i want to work with for the validation fucntions 
lists = [
    "hts_tst",
    "hts_tst_pos",
    "tx_new",
    "tx_curr",
    "tx_ml",
    "pmtct_stat",
    "pmtct_stat_pos",
    "pmtct_art",
    "tb_screen",
    "tb_pos",
    "vl_eligible",
    "vl_result_received",
    "vl_suppressed"
]

In [ ]:
# This function creates a 
def make_issue(df, mask, rule_id, description, observed):
    result = df.loc[
        mask,
        ["facility_id", "report_month"]
    ].copy()

    result["rule_id"] = rule_id
    result["description"] = description
    result["observed"] = observed.loc[mask].astype("string")

    return result[
        ["facility_id", "report_month", "rule_id", "description", "observed"]
    ]

In [300]:
def r1(df):
    mask = (
        df["hts_tst_pos"].notna() &
        df["hts_tst"].notna() &
        (df["hts_tst_pos"] > df["hts_tst"])
    )

    observed = (
        df["hts_tst_pos"].astype("string")
        + " > " +
        df["hts_tst"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R1",
        "hts_tst_pos must be less than or equal to hts_tst",
        observed
    )

In [301]:
def r2(df):
    condition_1 = (
        df["pmtct_stat_pos"].notna() &
        df["pmtct_stat"].notna() &
        (df["pmtct_stat_pos"] > df["pmtct_stat"])
    )

    condition_2 = (
        df["pmtct_art"].notna() &
        df["pmtct_stat_pos"].notna() &
        (df["pmtct_art"] > df["pmtct_stat_pos"])
    )

    mask = condition_1 | condition_2

    observed = (
        "pmtct_stat_pos=" + df["pmtct_stat_pos"].astype("string") +
        ", pmtct_stat=" + df["pmtct_stat"].astype("string") +
        ", pmtct_art=" + df["pmtct_art"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R2",
        "PMTCT cascade relationship is invalid",
        observed
    )

In [302]:
def r3(df):
    condition_1 = (
        df["vl_result_received"].notna() &
        df["vl_eligible"].notna() &
        (df["vl_result_received"] > df["vl_eligible"])
    )

    condition_2 = (
        df["vl_suppressed"].notna() &
        df["vl_result_received"].notna() &
        (df["vl_suppressed"] > df["vl_result_received"])
    )

    mask = condition_1 | condition_2

    observed = (
        "vl_eligible=" + df["vl_eligible"].astype("string") +
        ", vl_result_received=" + df["vl_result_received"].astype("string") +
        ", vl_suppressed=" + df["vl_suppressed"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R3",
        "Viral load cascade relationship is invalid",
        observed
    )

In [303]:
def r4(df):
    mask = (
        df["tb_pos"].notna() &
        df["tb_screen"].notna() &
        (df["tb_pos"] > df["tb_screen"])
    )

    observed = (
        df["tb_pos"].astype("string")
        + " > " +
        df["tb_screen"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R4",
        "tb_pos must be less than or equal to tb_screen",
        observed
    )

In [304]:
def r5(df):
    mask = df[lists].lt(0).any(axis=1)

    observed = df[lists].where(df[lists].lt(0)).apply(
        lambda row: row.dropna().to_dict(), axis=1).astype("string")

    return make_issue(
        df,
        mask,
        "R5",
        "Negative values are not allowed",
        observed
    )

In [305]:
def r6(df):
    valid = (
        df["hts_tst"].notna() &
        df["hts_tst_pos"].notna() &
        (df["hts_tst"] > 0) 
    )

    yield_pct = (
        df["hts_tst_pos"] / df["hts_tst"] * 100
    )

    mask = valid & (
        (yield_pct < 0.1) | (yield_pct > 15)
    )

    observed = yield_pct.round(2).astype("string") + "%"

    return make_issue(
        df, 
        mask,
        "R6",
        "HTS positively yield must be between 0.1%, and 15%",
        observed
    )

In [306]:
def r7(df):
    previous = (
        df.groupby("facility_id")
        ["hts_tst"].shift(1)
    )

    valid = (
        df["hts_tst"].notna() &
        previous.notna() &
        (previous > 0)
    )

    change_pct = (
        (df["hts_tst"] - previous).abs()
        /previous * 100)

    mask = valid & (change_pct >= 300)

    observed = change_pct.round(2).astype("string") + "% change"

    return make_issue(
        df, 
        mask,
        "R7",
        "Month-on-month change in hts_tst must be under 300%",
        observed
    )

In [307]:
def r8(df):
    count = (
        df.groupby("facility_id")
        ["report_month"].nunique()
    )

    incomplete_facilities = count[count != 36]

    mask = df["facility_id"].isin(
        incomplete_facilities.index
    )

    observed = (
        df["facility_id"].map(count).astype("string")+ "/36 monthly records"
    )

    return make_issue(
        df, 
        mask, 
        "R8",
        "Each facility should have 36 monthly recodrs",
        observed
    )

In [308]:
def r9(df):
    mask = (
        df["date_submitted"].notna()&
        df["report_month"].notna()&
        (df["date_submitted"] <= df["report_month"])
    )

    observed = (
        "submitted=" +
        df["date_submitted"].astype("string") + ", period_end=" + df["report_month"].astype("string")
    )

    return make_issue(
        df,
        mask,
        "R9",
        "date_submitted must be after the reporting period end",
        observed
    )

In [309]:
def r10(df):
    day_late = (
        df["date_submitted"] - df["report_month"]
    ).dt.days

    mask = (
        df["date_submitted"].notna()&
        df["report_month"].notna()&
        (day_late > 15)
    )

    observed = (
        day_late.astype("string") + " days"
    )

    return make_issue(
        df,
        mask,
        "R10",
        "Report should be submitted within 15 days of period end",
        observed
    )

In [310]:
def r11(df):
    previous_tx_curr = (
        df.groupby("facility_id")["tx_curr"].shift(1)
    )

    expected_tx_curr = (
        previous_tx_curr 
        + df["tx_new"]
        - df["tx_ml"]
    )

    valid = (
        previous_tx_curr.notna()&
        df["tx_curr"].notna()&
        df["tx_ml"].notna()&
        df["tx_new"].notna()
    )

    mask = valid & (
        df["tx_curr"] != expected_tx_curr
    )

    observed = (
        "actual=" +
        df["tx_curr"].astype("string") +
        ", expected=" +
        expected_tx_curr.astype("string")
    )

    return make_issue(
        df, 
        mask,
        "R11",
        "tx_curr should approximately equal previous tx_curr + tx_new - tx_ml",
        observed
    )

In [311]:
issues = pd.concat(
    [
        r1(df),
        r2(df),
        r3(df),
        r4(df),
        r5(df),
        r6(df),
        r7(df),
        r8(df),
        r9(df),
        r10(df),
        r11(df)
    ],
    ignore_index= True
)

In [312]:
issues.iloc[3200:3250]

,facility_id,report_month,rule_id,description,observed
3200,CRS011,2022-11-30,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3201,AKS010,2024-12-01,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3202,NAS999,2024-08-31,R8,Each facility should have 36 monthly recodrs,27/36 monthly records
3203,NAS015,2022-10-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3204,LAG011,2023-07-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3205,XXX999,2023-08-31,R8,Each facility should have 36 monthly recodrs,29/36 monthly records
3206,RIV007,2022-05-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3207,FCT001,2022-03-31,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3208,LAG009,2022-03-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3209,AKS002,2022-07-31,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3210,FCT001,2023-06-30,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3211,FCT013,2022-06-30,R8,Each facility should have 36 monthly recodrs,32/36 monthly records
3212,AKS002,2024-09-30,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3213,CRS011,2023-08-31,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3214,LAG008,2022-08-31,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3215,CRS010,2024-02-29,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3216,KAD004,2024-05-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3217,NAS004,2023-02-28,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3218,CRS007,2023-12-31,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3219,AKS004,2024-06-30,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3220,KAD007,2024-12-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3221,RIV008,2022-05-31,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3222,FCT001,2024-01-31,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3223,LAG015,2022-09-30,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3224,RIV007,2022-03-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3225,RIV001,2022-02-28,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3226,RIV014,2022-12-01,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3227,CRS014,2024-07-31,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3228,KAD010,2022-12-01,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3229,CRS009,2024-11-30,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3230,AKS005,2023-10-01,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3231,BEN008,2022-04-30,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3232,NAS999,2022-06-30,R8,Each facility should have 36 monthly recodrs,27/36 monthly records
3233,AKS013,2023-03-31,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3234,KAD006,2024-07-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3235,BEN008,2024-07-01,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3236,KAD005,2022-06-30,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3237,LAG015,2024-02-29,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3238,BEN008,2022-02-28,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3239,KAD005,2023-02-28,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3240,KAD003,2023-06-01,R8,Each facility should have 36 monthly recodrs,33/36 monthly records
3241,RIV007,2022-08-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3242,CRS008,2022-12-31,R8,Each facility should have 36 monthly recodrs,32/36 monthly records
3243,LAG015,2024-07-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3244,AKS013,2022-03-31,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3245,LAG015,2022-03-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3246,RIV002,2022-02-28,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3247,KAD006,2024-01-31,R8,Each facility should have 36 monthly recodrs,35/36 monthly records
3248,NAS001,2023-04-30,R8,Each facility should have 36 monthly recodrs,34/36 monthly records
3249,CRS002,2022-10-31,R8,Each facility should have 36 monthly recodrs,34/36 monthly records

In [313]:
issues["rule_id"].value_counts()

rule_id
R11    3773
R8     3520
R10    2204
R6      135
R1       50
R3       46
R7       44
R5       41
R2       21
R9       17
R4       10
Name: count, dtype: int64

In [314]:
issues.to_csv("issues_log", index = False)

In [315]:
ds = pd.read_csv("hts_age_sex_disaggregation_2024.csv")
ds.head()

  facility_id report_month     sex age_band hts_tst hts_tst_pos
0      AKS001      2024-01  Female      <15      24           0
1      AKS001      2024-01  Female    15-24      63           0
2      AKS001      2024-01  Female    25-34      63           0
3      AKS001      2024-01  Female    35-49      51         NaN
4      AKS001      2024-01  Female      50+      27           0

In [318]:
sex = {
    "Female": "Female",
    "female": "Female",
    "F": "Female",
    "f": "Female",
    "Male": "Male",
    "male": "Male",
    "M": "Male",
    "m": "Male"
}

ds["sex"] = ds["sex"].replace(sex)
ds["sex"].unique()

array(['Female', 'Male'], dtype=object)

In [319]:
ds["sex"].value_counts()

sex
Female    7200
Male      7200
Name: count, dtype: int64

In [320]:
ds["age_band"].value_counts()

age_band
25-34           2880
35-49           2880
<15             2703
15-24           2700
50+             2700
15 - 24          180
50 and above     180
0-14             177
Name: count, dtype: int64

In [321]:
age_map = {
    "<15": "0-14",
    "0-14": "0-14",
    "15-24": "15-24",
    "15 - 24": "15-24",
    "50+": "50+",
    "50 and above": "50+"
}

ds["age_band"] = ds["age_band"].replace(age_map)

In [322]:
ds["age_band"].unique()

array(['0-14', '15-24', '25-34', '35-49', '50+'], dtype=object)

In [334]:
ds["age_sex"] = (
    ds["sex"] + " " + ds["age_band"]
)

In [335]:
ds["age_sex"].head()

0     Female 0-14
1    Female 15-24
2    Female 25-34
3    Female 35-49
4      Female 50+
Name: age_sex, dtype: object

In [336]:
wide = ds.pivot_table(
    index=["facility_id", "report_month"],
    columns="age_sex",
    values=  "hts_tst",
    aggfunc="sum",
    fill_value=0
).reset_index()

In [338]:
wide.head()

age_sex,facility_id,report_month,Female 0-14,Female 15-24,Female 25-34,Female 35-49,Female 50+,Male 0-14,Male 15-24,Male 25-34,Male 35-49,Male 50+
0,AKS001,2024-01,24,63,63,51,27,14,48,53,34,16
1,AKS001,2024-02,32,113,123,91,37,25,89,90,55,26
2,AKS001,2024-03,33,99,93,76,31,25,57,77,54,26
3,AKS001,2024-04,30,86,117,81,32,23,67,84,53,23
4,AKS001,2024-05,34,110,117,90,37,30,81,80,65,23

In [340]:
wide.columns

Index(['facility_id', 'report_month', 'Female 0-14', 'Female 15-24',
       'Female 25-34', 'Female 35-49', 'Female 50+', 'Male 0-14', 'Male 15-24',
       'Male 25-34', 'Male 35-49', 'Male 50+'],
      dtype='object', name='age_sex')

In [343]:
long_again = wide.melt(
    id_vars=["facility_id", "report_month"],
    var_name="sex_age",
    value_name="value"
)
long_again.head()

  facility_id report_month      sex_age value
0      AKS001      2024-01  Female 0-14    24
1      AKS001      2024-02  Female 0-14    32
2      AKS001      2024-03  Female 0-14    33
3      AKS001      2024-04  Female 0-14    30
4      AKS001      2024-05  Female 0-14    34