In [8]:
# Imported the csv file 
import pandas as pd
df = pd.read_csv('facility_service_data_2022_2024.csv')

df.head(5)

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,Mission Hospital Bwari II,FCT,Bwari,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,Teaching Hospital Gwagwalada II,FCT,Gwagwalada,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,Nasarawa,Lafia,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,Lagos,Surulere,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,Comprehensive Health Centre Oron,Akwa-Ibom,Oron,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk

In [9]:
# Changed the facility name, id's, state, and lga to uppercase.
df['state'] = df['state'].str.strip().str.upper()
df['facility_name'] = df['facility_name'].str.strip().str.upper()
df['facility_id'] = df['facility_id'].str.strip().str.upper()
df['lga'] = df['lga'].str.strip().str.upper()
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,128,4,3,1286,21,1279,1179,968,2024-09-13,Data Clerk
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,30/11/2024,306,20,16,722,3,43,2,1,555,8,520,427,388,2024-12-18,Data Clerk
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [22]:
# Changed the dated to pandas date and time format
cols = ["report_month", "date_submitted"]

df[cols] = df[cols].apply(
    lambda col: pd.to_datetime(col, format="mixed" ,errors="coerce")
)
df[cols]

C:\Users\USER\AppData\Local\Temp\ipykernel_9780\1334786398.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[cols] = df[cols].apply(

     report_month date_submitted
0      2022-11-30     2022-12-11
1      2023-04-30     2023-05-11
2      2024-01-31     2024-02-18
3      2022-03-31     2022-04-15
4      2022-01-31     2022-02-13
...           ...            ...
4409   2024-08-31     2024-09-13
4410   2024-11-30     2024-12-18
4411   2022-04-30     2022-05-13
4412   2022-03-31     2022-04-11
4413   2024-09-30     2024-10-15

[4355 rows x 2 columns]

In [11]:
# Created a seperate column for year, month and quarter
df['year'] = df['report_month'].dt.year
df['month'] = df['report_month'].dt.month
df['quarter'] = df['report_month'].dt.quarter
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,...,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by,year,month,quarter
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,952,39,29,"2,721",23,...,2237,36,2271,1624,1396,2022-12-11,Data Clerk,2022,11,4
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,773,40,34,5094,42,...,2875,41,3722,2467,2342,2023-05-11,Data Clerk,2023,4,2
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,...,526,6,753,520,476,2024-02-18,Data Clerk,2024,1,1
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,...,375,8,451,383,358,2022-04-15,Facility Focal Person,2022,3,1
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,...,736,19,1145,685,644,2022-02-13,Data Clerk,2022,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,...,1286,21,1279,1179,968,2024-09-13,Data Clerk,2024,8,3
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,2024-11-30,306,20,16,722,3,...,555,8,520,427,388,2024-12-18,Data Clerk,2024,11,4
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,...,403,11,573,316,306,2022-05-13,M&E Officer,2022,4,2
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,...,435,8,453,405,380,2022-04-11,Facility Focal Person,2022,3,1
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,...,558,21,661,443,387,2024-10-15,Data Clerk,2024,9,3

In [12]:
# Moved the year, month and quarter column from the end to just beside the report_month column from better reading
cols = df.columns.tolist()
cols.remove('year')
cols.remove('month')
cols.remove('quarter')

cols.insert(5, 'year')
cols.insert(6, 'month')
cols.insert(7, 'quarter')
df = df[cols]
df.tail(3)

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,2022,4,2,323,3,...,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,2022,3,1,128,,...,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,2024,9,3,544,7,...,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [13]:
# validating the dates to make sure they fall under 2022 - 2024 and end of the month 
valid_dates = (
    df["report_month"].dt.year.between(2022, 2024)
    & df["report_month"].dt.is_month_end
)

df.loc[~valid_dates, "report_month"]

5      2022-05-01
10     2024-06-01
11     2023-02-01
24     2022-12-01
38     2024-12-01
          ...
4382   2023-01-01
4383   2022-03-01
4394   2024-12-01
4399   2023-12-01
4406   2023-11-01
Name: report_month, Length: 441, dtype: datetime64[ns]

In [14]:
df.replace(["", "N/A", "-", 'NULL', "nil"], pd.NA, inplace= True)

In [15]:
df

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,2022,11,4,952,39,...,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,2023,4,2,773,40,...,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,2024,1,1,244,6,...,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,2022,3,1,440,6,...,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,2022,1,1,76,0,...,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,2024,8,3,541,19,...,128,4,3,1286,21,1279,1179,968,2024-09-13,Data Clerk
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,2024-11-30,2024,11,4,306,20,...,43,2,1,555,8,520,427,388,2024-12-18,Data Clerk
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,2022,4,2,323,3,...,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,2022,3,1,128,,...,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,2024,9,3,544,7,...,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [16]:
# Removed commas white spaces and convertes all the numbers from text to number 
cols = ["hts_tst", "hts_tst_pos", "tx_new", "tx_curr", "tx_ml", "pmtct_stat", "pmtct_stat_pos", "pmtct_art", "tb_screen", "tb_pos", "vl_eligible", "vl_result_received", "vl_suppressed"]

df[cols] = (df[cols].replace(",", "")
    .apply(lambda col: col.astype("string").str.strip())
    .apply(pd.to_numeric, errors="coerce"))

In [17]:
df

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,2022,11,4,952.0,39.0,...,300.0,9,8,2237.0,36,2271.0,1624.0,1396.0,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,2023,4,2,773.0,40.0,...,102.0,1,0,2875.0,41,3722.0,2467.0,2342.0,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,2024,1,1,244.0,6.0,...,58.0,1,0,526.0,6,753.0,520.0,476.0,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,2022,3,1,440.0,6.0,...,92.0,0,0,375.0,8,451.0,383.0,358.0,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,2022,1,1,76.0,0.0,...,18.0,1,0,736.0,19,1145.0,685.0,644.0,2022-02-13,Data Clerk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,2024,8,3,541.0,19.0,...,128.0,4,3,1286.0,21,1279.0,1179.0,968.0,2024-09-13,Data Clerk
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,2024-11-30,2024,11,4,306.0,20.0,...,43.0,2,1,555.0,8,520.0,427.0,388.0,2024-12-18,Data Clerk
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,2022,4,2,323.0,3.0,...,84.0,3,2,403.0,11,573.0,316.0,306.0,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,2022,3,1,128.0,<NA>,...,23.0,0,0,435.0,8,453.0,405.0,380.0,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,2024,9,3,544.0,7.0,...,97.0,2,1,558.0,21,661.0,443.0,387.0,2024-10-15,Data Clerk

In [18]:
# checked the number of duplicates in the dataset
df.duplicated().sum()

59

In [19]:
# Removed duplicates from the dataset
df = df.drop_duplicates(keep="first")

In [27]:
df.isna().sum()

facility_id             0
facility_name           0
state                   0
lga                     0
report_month            0
year                    0
month                   0
quarter                 0
hts_tst                77
hts_tst_pos            78
tx_new                 76
tx_curr               139
tx_ml                   0
pmtct_stat             77
pmtct_stat_pos          0
pmtct_art               0
tb_screen              79
tb_pos                  0
vl_eligible            78
vl_result_received     77
vl_suppressed          76
date_submitted          0
reported_by             0
dtype: int64

In [30]:
fm= pd.read_csv("facility_master_list.csv")
fm.head(5)

,facility_id,facility_name,state,lga,facility_level,ownership,setting,art_start_date,catchment_population,latitude,longitude
0,AKS001,Comprehensive Health Centre Uyo,Akwa Ibom,Uyo,Primary,Private,Urban,2015-04-22,79792.0,10.09626,9.47271
1,AKS002,General Hospital Ikot Ekpene,Akwa Ibom,Ikot Ekpene,Secondary,Public,Urban,2013-09-22,49951.0,7.01753,4.10253
2,AKS003,Model Primary Health Centre Eket,Akwa Ibom,Eket,Primary,Public,Rural,2022-04-04,32449.0,8.46012,3.03009
3,AKS004,Comprehensive Health Centre Etinan,Akwa Ibom,Etinan,Primary,Public,Rural,2018-09-03,193467.0,8.67776,5.11477
4,AKS005,Comprehensive Health Centre Oron,Akwa Ibom,Oron,Primary,Public,Rural,2020-08-04,72505.0,10.62470,4.38552

In [32]:
fm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   facility_id           126 non-null    object
 1   facility_name         126 non-null    object
 2   state                 126 non-null    object
 3   lga                   126 non-null    object
 4   facility_level        126 non-null    object
 5   ownership             120 non-null    object
 6   setting               120 non-null    object
 7   art_start_date        126 non-null    object
 8   catchment_population  120 non-null    float64
 9   latitude              126 non-null    float64
 10  longitude             126 non-null    float64
dtypes: float64(3), object(8)
memory usage: 11.0+ KB

In [71]:
fm["facility_id"].is_unique

True

In [72]:
master_duplicates = fm[
    fm["facility_id"].duplicated(keep=False)
]

master_duplicates

Empty DataFrame
Columns: [facility_id, facility_name, state, lga, facility_level, ownership, setting, art_start_date, catchment_population, latitude, longitude]
Index: []

In [74]:
fm["facility_id"].head()

0    AKS001
1    AKS002
2    AKS003
3    AKS004
4    AKS005
Name: facility_id, dtype: string

In [61]:
fm.isna().sum()

facility_id             0
facility_name           0
state                   0
lga                     0
facility_level          0
ownership               6
setting                 6
art_start_date          0
catchment_population    6
latitude                0
longitude               0
dtype: int64

In [53]:
fm["facility_id"].dtype

dtype('O')

In [58]:
fm.drop_duplicates(subset=["facility_id"], keep="first", inplace=True)

In [62]:
fm["facility_id"] = (fm["facility_id"].astype("string").str.strip().str.upper())

In [65]:
merged = df.merge(
    fm,
    on="facility_id",
    how="outer",
    indicator=True
)

In [67]:
merged["_merge"].value_counts()

_merge
both          4175
left_only      180
right_only       5
Name: count, dtype: int64

In [69]:
in_both = merged[merged["_merge"] == "both"]

In [75]:
len(in_both)

4175