In [169]:
import pandas as pd

df = pd.read_csv("facility_service_data_2022_2024.csv", dtype = str)
df.head(50)

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,Mission Hospital Bwari II,FCT,Bwari,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,Teaching Hospital Gwagwalada II,FCT,Gwagwalada,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,Nasarawa,Lafia,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,Lagos,Surulere,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,Comprehensive Health Centre Oron,Akwa-Ibom,Oron,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
5,LAG015,MODEL PRIMARY HEALTH CENTRE BADAGRY II,Lagos,Badagry,May-2022,259,13,11,1141,12,49,2,1,923,26,777,523,501,2022-06-18,M&E Officer
6,FCT001,Mission Hospital AMAC,FCT,AMAC,28/02/2022,881,3,2,1385,15,212,2,1,950,13,975,908,814,2022-03-16,Data Clerk
7,FCT009,Model Primary Health Centre Kuje II,FCT,Kuje,28/02/2023,119,4,3,442,5,17,2,1,256,1,331,211,193,2023-03-13,Data Clerk
8,KAD012,Comprehensive Health Centre Kaduna South II,Kaduna,Kaduna South,2022-07-31,402,4,3,647,8,91,0,0,386,9,555,306,293,2022-08-11,Facility Focal Person
9,NAS004,Cottage Hospital Akwanga,Nasarawa,Akwanga,2023-09-30,357,15,13,505,4,70,2,1,303,5,352,318,306,2023-10-13,Facility Focal Person
10,NAS004,Cottage Hospital Akwanga,Nasarawa,Akwanga,Jun-2024,382,16,15,567,3,120,2,1,538,12,500,306,284,2024-07-21,M&E Officer
11,NAS011,Mission Hospital Lafia II,Nasarawa,Lafia,Feb-2023,979,7,5,2673,15,205,1,0,2457,40,1887,1769,1555,2023-03-13,Facility Focal Person
12,KAD014,General Hospital Sabon Gari II,Kaduna,Sabon Gari,2023-09-30,236,2,1,2393,39,70,2,1,1466,37,1814,1108,975,2023-10-16,M&E Officer
13,RIV014,Cottage Hospital Obio/Akpor II,Rivers,Obio/Akpor,2023-05-31,1383,10,8,635,7,320,0,0,528,8,577,402,388,2023-06-18,M&E Officer
14,CRS003,Specialist Hospital Ogoja,Cross River,Ogoja,2022-01-31,1071,42,35,5623,113,247,9,8,5025,100,3883,2563,2119,2022-03-01,Data Clerk
15,BEN012,Cottage Hospital Vandeikya II,Benue,Vandeikya,2023-02-28,610,2,1,458,6,95,0,0,291,7,420,247,236,2023-03-18,Facility Focal Person
16,FCT007,Specialist Hospital Bwari II,FCT,Bwari,2022-08-31,1755,37,33,4470,29,198,2,1,4084,78,3985,3089,2670,2022-09-16,Data Clerk
17,NAS010,Teaching Hospital Nasarawa II,Nasarawa,Nasarawa,2024-01-31,1764,83,77,5265,19,225,10,7,4767,86,4608,2632,2328,2024-02-11,M&E Officer
18,AKS008,PRIMARY HEALTH CENTRE UYO II,Akwa Ibom,Uyo,2024-12-31,81,2,1,95,0,17,0,0,55,1,68,45,43,2025-01-15,Facility Focal Person
19,LAG005,Mission Hospital Agege,Lagos,Agege,2022-10-31,1124,30,24,1580,13,220,1,0,1493,32,1398,1300,1182,2022-11-11,M&E Officer
20,BEN012,Cottage Hospital Vandeikya II,Benue,Vandeikya,2024-09-30,561,7,5,456,9,175,0,0,313,6,347,286,259,2024-10-18,Facility Focal Person
21,CRS006,Primary Health Centre Calabar Municipal II,Cross-River,Calabar Municipal,2023-02-28,527,23,21,1303,13,112,2,1,878,17,1049,650,563,2023-03-16,Data Clerk
22,AKS004,Comprehensive Health Centre Etinan,AKWA IBOM,Etinan,28/02/2022,147,6,5,1012,11,17,0,0,884,18,754,606,631,2022-03-13,M&E Officer
23,BEN011,Model Primary Health Centre Katsina-Ala II,Benue,Katsina-Ala,2023-07-31,267,9,6,346,6,66,2,1,249,7,292,274,241,2023-08-11,M&E Officer
24,aks011,Comprehensive Health Centre Etinan II,Akwa Ibom,Etinan,Dec-2022,109,6,4,3040,3,27,3,2,245,5,213,149,133,2023-01-21,M&E Officer
25,CRS009,Comprehensive Health Centre Obudu II,Cross River,Obudu,2023-04-30,533,22,17,8280,11,127,4,3,541,9,678,411,379,2023-05-18,M&E Officer
26,AKS008,Primary Health Centre Uyo II,Akwa Ibom,Uyo,2022-01-31,77,0,0,83,0,17,0,0,72,1,57,35,29,2022-02-15,Facility Focal Person
27,FCT008,Teaching Hospital Gwagwalada II,Federal Capital Territory,Gwagwalada,2022-08-31,840,50,46,5303,80,221,6,5,3927,77,4651,4053,3350,2022-09-21,Facility Focal Person
28,BEN013,Model Primary Health Centre Makurdi II,Benue,Makurdi,2022-03-31,490,13,12,304,2,134,2,1,173,6,211,136,122,2022-04-16,Data Clerk
29,FCT011,COTTAGE HOSPITAL AMAC II,FCT,AMAC,2023-05-31,409,14,13,2183,6,116,2,1,1868,25,2007,1647,1492,2023-06-13,Facility Focal Person
30,KAD007,Model Primary Health Centre Kaduna South II,Kaduna,Kaduna South,2024-06-30,293,14,10,"1,114",19,70,1,0,1007,24,1003,627,578,2024-07-16,M&E Officer
31,CRS015,Model Primary Health Centre Akamkpa II,cross river,Akamkpa,2023-09-30,97,0,0,521,8,26,0,0,392,6,448,352,307,2023-10-15,Data Clerk
32,FCT011,Cottage Hospital AMAC II,FCT,AMAC,2022-03-31,308,10,7,2362,23,74,3,2,1369,21,1959,1797,1594,2022-04-11,M&E Officer
33,RIV003,Comprehensive Health Centre Khana,Rivers,Khana,2023-02-28,205,11,8,1026,15,28,1,0,968,12,895,709,671,2023-03-13,M&E Officer
34,RIV006,Cottage Hospital Eleme,Rivers,Eleme,2022-01-31,893,49,38,2262,37,191,6,5,2004,45,1948,1812,1508,2022-02-11,Facility Focal Person
35,FCT007,Specialist Hospital Bwari II,FCT,Bwari,2022-03-31,1552,32,27,4570,47,292,3,2,3240,59,4159,2719,2435,2022-04-13,M&E Officer
36,LAG003,Teaching Hospital Badagry,Lagos,Badagry,31/03/2024,3384,3407,123,6685,106,477,9,7,5705,92,5388,4374,4226,2024-04-21,Facility Focal Person
37,NAS007,General Hospital Karu II,Nasarawa,Karu,2024-04-30,761,8,7,2110,18,144,1,0,1830,28,1735,1273,1113,2024-05-11,M&E Officer
38,CRS014,Comprehensive Health Centre Obudu II,Cross River,Obudu,Dec-2024,387,6,4,211,0,90,0,0,139,3,148,89,,2025-02-15,M&E Officer
39,LAG011,Cottage Hospital Agege II,Lagos,Agege,2022-08-31,681,2,1,1788,14,190,4,3,1608,22,1273,1105,1020,2022-09-16,Facility Focal Person
40,KAD010,Cottage Hospital Chikun II,Kaduna,Chikun,2023-08-31,246,9,7,968,6,52,0,0,914,21,890,631,530,2023-09-13,Facility Focal Person
41,FCT011,Cottage Hospital AMAC II,FCT,AMAC,2024-04-30,459,13,12,2050,23,56,2,1,1540,36,1773,1416,1291,2024-05-11,Facility Focal Person
42,NAS003,COTTAGE HOSPITAL KEFFI,Nasarawa,Keffi,2022-05-31,265,1,0,"1,878",14,79,0,0,1202,24,1374,1104,1036,2022-06-13,Facility Focal Person
43,BEN015,Primary Health Centre Otukpo II,Benue,Otukpo,2024-09-30,170,6,4,723,9,38,0,0,666,16,522,316,289,2024-10-13,Facility Focal Person
44,KAD004,Specialist Hospital Sabon Gari,Kaduna,Sabon Gari,30/06/2023,3433,134,114,4666,46,883,21,17,3161,62,3226,2630,2403,2023-07-13,M&E Officer
45,RIV002,TEACHING HOSPITAL OBIO/AKPOR,RIVERS,Obio/Akpor,2023-12-31,1558,29,28,4389,58,386,5,3,3433,60,4072,2665,2228,2024-01-15,M&E Officer
46,RIV010,Teaching Hospital Ahoada East II,Rivers,Ahoada East,2022-06-30,756,11,-27,3307,24,174,4,3,2272,48,3052,2439,2092,2022-07-21,M&E Officer
47,NAS013,General Hospital Keffi II,Nasarawa,Keffi,31/01/2024,556,26,20,1647,4,131,4,3,1262,25,1296,1150,1020,2024-02-15,Data Clerk
48,LAG099,General Hospital Chikun II,Kaduna,Chikun,2024-05-31,361,11,10,1573,28,89,2,1,950,20,1235,1100,1006,2024-06-13,Facility Focal Person
49,NAS010,Teaching Hospital Nasarawa II,Nasarawa,Nasarawa,2022-12-31,1729,92,77,4742,42,175,7,6,4148,71,3930,3193,2915,2023-01-15,Facility Focal Person

In [170]:
df.isna().sum()

facility_id            0
facility_name          0
state                  0
lga                    0
report_month           0
hts_tst               40
hts_tst_pos           38
tx_new                37
tx_curr                0
tx_ml                  0
pmtct_stat            37
pmtct_stat_pos         0
pmtct_art              0
tb_screen             41
tb_pos                 0
vl_eligible           43
vl_result_received    32
vl_suppressed         44
date_submitted         0
reported_by            0
dtype: int64

In [171]:
df.shape

(4414, 20)

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4414 entries, 0 to 4413
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   facility_id         4414 non-null   object
 1   facility_name       4414 non-null   object
 2   state               4414 non-null   object
 3   lga                 4414 non-null   object
 4   report_month        4414 non-null   object
 5   hts_tst             4344 non-null   object
 6   hts_tst_pos         4355 non-null   object
 7   tx_new              4349 non-null   object
 8   tx_curr             4414 non-null   object
 9   tx_ml               4414 non-null   object
 10  pmtct_stat          4348 non-null   object
 11  pmtct_stat_pos      4414 non-null   object
 12  pmtct_art           4414 non-null   object
 13  tb_screen           4349 non-null   object
 14  tb_pos              4414 non-null   object
 15  vl_eligible         4347 non-null   object
 16  vl_result_received  4347 non-null   object
 17  vl_suppressed       4346 non-null   object
 18  date_submitted      4414 non-null   object
 19  reported_by         4414 non-null   object
dtypes: object(20)
memory usage: 689.8+ KB

In [191]:
# Organizing the facility name, states and, facility id's

df["state"] = df["state"].str.strip().str.upper()
df["facility_name"]= df["facility_name"].str.strip().str.upper()
df["facility_id"]= df["facility_id"].str.strip().str.upper()
df["lga"]= df["lga"].str.strip().str.upper()
df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,30/11/2022,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,30/04/2023,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,128,4,3,1286,21,1279,1179,968,2024-09-13,Data Clerk
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,30/11/2024,306,20,16,722,3,43,2,1,555,8,520,427,388,2024-12-18,Data Clerk
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,84,3,2,403,11,573,316,306,2022-05-13,M&E Officer
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,23,0,0,435,8,453,405,380,2022-04-11,Facility Focal Person
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,97,2,1,558,21,661,443,387,2024-10-15,Data Clerk

In [205]:
# Organizing the report months and dates submitted
df["report_month"] = pd.to_datetime(df["report_month"], format= "mixed")
df["date_submitted"] = pd.to_datetime(df["date_submitted"], format ="mixed")
df.head(5)

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,952,39,29,"2,721",23,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,773,40,34,5094,42,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk

In [208]:
df['year'] = df['report_month'].dt.year
df['month'] = df['report_month'].dt.month
df['quarter'] = df['report_month'].dt.quarter

df

,facility_id,facility_name,state,lga,report_month,hts_tst,hts_tst_pos,tx_new,tx_curr,tx_ml,...,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by,year,month,quarter
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,952,39,29,"2,721",23,...,2237,36,2271,1624,1396,2022-12-11,Data Clerk,2022,11,4
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,773,40,34,5094,42,...,2875,41,3722,2467,2342,2023-05-11,Data Clerk,2023,4,2
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,244,6,5,952,11,...,526,6,753,520,476,2024-02-18,Data Clerk,2024,1,1
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,440,6,4,630,8,...,375,8,451,383,358,2022-04-15,Facility Focal Person,2022,3,1
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,76,0,0,1332,12,...,736,19,1145,685,644,2022-02-13,Data Clerk,2022,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4409,CRS006,PRIMARY HEALTH CENTRE CALABAR MUNICIPAL II,CROSS RIVER,CALABAR MUNICIPAL,2024-08-31,541,19,16,1437,11,...,1286,21,1279,1179,968,2024-09-13,Data Clerk,2024,8,3
4410,AKS013,MODEL PRIMARY HEALTH CENTRE ABAK II,AKWA IBOM,ABAK,2024-11-30,306,20,16,722,3,...,555,8,520,427,388,2024-12-18,Data Clerk,2024,11,4
4411,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-04-30,323,3,2,660,7,...,403,11,573,316,306,2022-05-13,M&E Officer,2022,4,2
4412,NAS001,MODEL PRIMARY HEALTH CENTRE LAFIA,NASARAWA,LAFIA,2022-03-31,128,,1,502,5,...,435,8,453,405,380,2022-04-11,Facility Focal Person,2022,3,1
4413,RIV009,MISSION HOSPITAL KHANA II,RIVERS,KHANA,2024-09-30,544,7,4,764,8,...,558,21,661,443,387,2024-10-15,Data Clerk,2024,9,3

In [219]:
df.columns

cols = df.columns.to_list()
cols.remove("year")
cols.remove("month")
cols.remove("quarter")

cols.insert(5, "year")
cols.insert(6, "month")
cols.insert(7, "quarter")

df = df[cols]
df.head(10)

,facility_id,facility_name,state,lga,report_month,year,month,quarter,hts_tst,hts_tst_pos,...,pmtct_stat,pmtct_stat_pos,pmtct_art,tb_screen,tb_pos,vl_eligible,vl_result_received,vl_suppressed,date_submitted,reported_by
0,FCT012,MISSION HOSPITAL BWARI II,FCT,BWARI,2022-11-30,2022,11,4,952,39,...,300,9,8,2237,36,2271,1624,1396,2022-12-11,Data Clerk
1,FCT008,TEACHING HOSPITAL GWAGWALADA II,FCT,GWAGWALADA,2023-04-30,2023,4,2,773,40,...,102,1,0,2875,41,3722,2467,2342,2023-05-11,Data Clerk
2,NAS006,PRIMARY HEALTH CENTRE LAFIA II,NASARAWA,LAFIA,2024-01-31,2024,1,1,244,6,...,58,1,0,526,6,753,520,476,2024-02-18,Data Clerk
3,LAG004,COMPREHENSIVE HEALTH CENTRE SURULERE,LAGOS,SURULERE,2022-03-31,2022,3,1,440,6,...,92,0,0,375,8,451,383,358,2022-04-15,Facility Focal Person
4,AKS005,COMPREHENSIVE HEALTH CENTRE ORON,AKWA-IBOM,ORON,2022-01-31,2022,1,1,76,0,...,18,1,0,736,19,1145,685,644,2022-02-13,Data Clerk
5,LAG015,MODEL PRIMARY HEALTH CENTRE BADAGRY II,LAGOS,BADAGRY,2022-05-01,2022,5,2,259,13,...,49,2,1,923,26,777,523,501,2022-06-18,M&E Officer
6,FCT001,MISSION HOSPITAL AMAC,FCT,AMAC,2022-02-28,2022,2,1,881,3,...,212,2,1,950,13,975,908,814,2022-03-16,Data Clerk
7,FCT009,MODEL PRIMARY HEALTH CENTRE KUJE II,FCT,KUJE,2023-02-28,2023,2,1,119,4,...,17,2,1,256,1,331,211,193,2023-03-13,Data Clerk
8,KAD012,COMPREHENSIVE HEALTH CENTRE KADUNA SOUTH II,KADUNA,KADUNA SOUTH,2022-07-31,2022,7,3,402,4,...,91,0,0,386,9,555,306,293,2022-08-11,Facility Focal Person
9,NAS004,COTTAGE HOSPITAL AKWANGA,NASARAWA,AKWANGA,2023-09-30,2023,9,3,357,15,...,70,2,1,303,5,352,318,306,2023-10-13,Facility Focal Person

In [ ]:
# Validating the dates between 2022 - 2024 and month end 
valid_dates = (
    df["report_month"].dt.year.between(2022, 2024)
    & df["report_month"].dt.is_month_end
)

print(df.loc[~valid_dates, "report_month"])

5      2022-05-01
10     2024-06-01
11     2023-02-01
24     2022-12-01
38     2024-12-01
          ...
4382   2023-01-01
4383   2022-03-01
4394   2024-12-01
4399   2023-12-01
4406   2023-11-01
Name: report_month, Length: 441, dtype: datetime64[ns]